<a href="https://colab.research.google.com/github/AvkashSharma/COMP472/blob/master/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example Heading 1

## Example Heading 1.1

In [4]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
%matplotlib inline

print('testing jupyter')

testing jupyter


# Base-DT-DS1
a baseline Decision Tree using entropy as decision criterion and using default values values for the rest of the parameters

## Importing Libraries

In [32]:
import numpy as np
import pandas as pd

## Importing and Splitting the dataset

In [44]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training the DT model on the Training set

In [77]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_training_1,Y_training_1)

DecisionTreeClassifier(criterion='entropy')

## Sample prediction using X_Validate_1

In [67]:
Y_validate1_pred = classifier.predict(X_validate_1)

## Applying Classifier on Test set

In [68]:
Y_test1_pred = classifier.predict(X_test1)

## Confusion Matrix and Classification Report

In [75]:
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
cr = classification_report(Y_test1, Y_test1_pred)
print(cr)

[[3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 

## Output file containing output classification

In [95]:
pd.DataFrame(cm).to_csv('Base-DT-DS1.csv', header = None, index = None)

# Base-DT-DS2

## Importing and Splitting the dataset

In [84]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training the DT model on the Training set

In [87]:
classifier.fit(X_training_2,Y_training_2)

DecisionTreeClassifier(criterion='entropy')

## Sample prediction using X_Validate_2

In [88]:
Y_validate2_pred = classifier.predict(X_validate_2)

## Applying Classifier on Test set

In [89]:
Y_test2_pred = classifier.predict(X_test2)

## Confusion Matrix and Classification Report

In [104]:
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
print(cm2)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cr2)

[[ 44   3   1   0   4   0   0   0   0   3]
 [  1 119   0   1   0   2   0   0   2   0]
 [  0   0   8   0   0   2   0   0   3   2]
 [  0   4   0  10   0   1   0   0   0   0]
 [  2   3   1   2  23   2   0   1   2  14]
 [  0   0   2   1   2  41   0   0   0   9]
 [  1   0   2   0   1   1   7   0   2   1]
 [  0   2   0   0   0   0   0  12   1   0]
 [  2   1   0   1   0   0   0   0  43   3]
 [  3   1   2   0   8   9   0   0   2 100]]
              precision    recall  f1-score   support

           0       0.83      0.80      0.81        55
           1       0.89      0.95      0.92       125
           2       0.50      0.53      0.52        15
           3       0.67      0.67      0.67        15
           4       0.61      0.46      0.52        50
           5       0.71      0.75      0.73        55
           6       1.00      0.47      0.64        15
           7       0.92      0.80      0.86        15
           8       0.78      0.86      0.82        50
           9       0.76     

## Output file containing output classification

In [118]:
pf2 = pd.DataFrame(cm2)
pf2.to_csv('Base-DT-DS2.csv', header = None, index = None)

# Sharma power

# Best-DT
a better performing Decision Tree found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* splitting criterion: gini and entropy
* maximum depth of the tree: 10 and no maximum
* minimum number of samples to split an internal node: experiment with values of your choice
* minimum impurity decrease: experiment with values of your choice
* class weight: None and balanced

# PER
 a Perceptron, with default parameter values

# Base-MLP
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent