<a href="https://colab.research.google.com/github/AvkashSharma/COMP472/blob/master/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example Heading 1

## Example Heading 1.1

In [3]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
%matplotlib inline

print('testing jupyter')

testing jupyter


# GNB-DS1
Gaussian Naive Bayes Classifier, with default parameter values

# GNB-DS2
Gaussian Naive Bayes Classifier, with default parameter values

## GNB-DS1

### Importing Libraries

In [18]:
import numpy as np
import pandas as pd

### Importing and Splitting the Dataset

In [19]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_1,Y_training_1)

GaussianNB(priors=None, var_smoothing=1e-09)

### Sample prediction using X_Validate_1

In [7]:
Y_validate1_pred = classifier.predict(X_validate_1)

### Applying Classifier on Test set

In [8]:
Y_test1_pred = classifier.predict(X_test1)

### Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
accuracy_score(Y_test1, Y_test1_pred)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

0.6875

### Output file containing output classification

In [35]:
pd.DataFrame(Y_test1_pred).to_csv('GNB-DS1.csv', header = None)

## GNB-DS2

### Importing and splitting the Dataset

In [29]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test1_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test1_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train1.iloc[:, :-1].values
Y_training_2 = dataset_train1.iloc[:, -1].values
X_validate_2 = dataset_validate1.iloc[:, :-1].values
Y_validate_2 = dataset_validate1.iloc[:, -1].values
X_test2 = dataset_test1_no_label_2.iloc[:, ].values
Y_test2 = dataset_test1_with_label_2.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [30]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_2,Y_training_2)

GaussianNB(priors=None, var_smoothing=1e-09)

### Sample prediction using X_Validate_2

In [31]:
Y_validate2_pred = classifier.predict(X_validate_2)
print(np.concatenate((Y_validate2_pred.reshape(len(Y_validate2_pred),1), Y_validate_2.reshape(len(Y_validate_2),1)),1))

[[ 1  1]
 [17 17]
 [22 12]
 [ 1 12]
 [ 1  1]
 [16 16]
 [17 17]
 [25 25]
 [14 14]
 [ 9  9]
 [ 3  3]
 [ 4  4]
 [22 21]
 [12 17]
 [25 25]
 [17 10]
 [16 18]
 [15 15]
 [11 11]
 [25 15]
 [ 5  5]
 [ 8  8]
 [19 19]
 [21 21]
 [24 24]
 [12 22]
 [15 15]
 [18 18]
 [14 20]
 [ 4  4]
 [15 15]
 [20 20]
 [20 20]
 [17  0]
 [24 24]
 [17 17]
 [10 10]
 [13 13]
 [ 8  8]
 [23 23]
 [ 3  3]
 [ 8 19]
 [18 18]
 [20 20]
 [17  7]
 [ 1  9]
 [25 25]
 [22 22]
 [ 8  8]
 [ 2  2]
 [10 10]
 [21 23]
 [13 12]
 [ 0  7]
 [16 16]
 [12  9]
 [ 2  2]
 [ 6  6]
 [ 3  3]
 [14 14]
 [11 11]
 [12  6]
 [ 3  3]
 [13 21]
 [12 23]
 [14 14]
 [ 1 17]
 [16  9]
 [22 22]
 [11 11]
 [10 10]
 [17  8]
 [ 3  3]
 [ 1  4]
 [ 1  7]
 [18 18]
 [ 8  8]
 [ 4  2]
 [25 25]
 [14 14]
 [ 1 12]
 [12 20]
 [ 5 19]
 [25 25]
 [ 7  7]
 [12  6]
 [17  0]
 [18 18]
 [ 3 14]
 [12 12]
 [19 19]
 [ 0 10]
 [23 23]
 [ 5  5]
 [25 25]
 [12 16]
 [ 2  2]
 [12  0]
 [21 21]
 [25 25]
 [16  6]
 [16 14]
 [12 13]
 [13 13]
 [ 7  7]
 [15 13]
 [12 13]
 [ 9  9]
 [ 0 13]
 [13 13]
 [ 5  5]
 

### Applying Classifier on Test sets

In [32]:
Y_test2_pred = classifier.predict(X_test2)

### Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test2, Y_test2_pred)
print(cm)
accuracy_score(Y_test2, Y_test2_pred)

[[  0   7   0   0   0   1   0   0   0   0  44   0   0   1   2   0   0   0
    0   0   0]
 [  0   1   0   0   0   0   0   0   0   0 102   0   0   3   2   0   0  17
    0   0   0]
 [  2   8   0   0   0   0   0   0   0   0   1   0   3   0   1   0   0   0
    0   0   0]
 [  0   0   0   1   0   0   0   0   0   0  10   0   0   3   1   0   0   0
    0   0   0]
 [  0  16   0   1   0   0   0   0   0   0  13   2   5   1   1   0   1   1
    0   5   4]
 [  0  38   0   2   1   2   0   0   0   1   0   0   0   0   8   3   0   0
    0   0   0]
 [  2   4   0   0   0   0   0   0   0   1   3   0   0   1   3   0   0   0
    1   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   2   0   0   0   2
    0   0   0]
 [  5   9   0   1   0   0   0   0   0   0  12   4  13   0   2   0   0   0
    0   0   4]
 [  4  46   0   7   0   0   0   0   0   0   5   0  12   0  32   1   6   0
    0   3   9]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

0.007692307692307693

### Output file containing output classification

In [36]:
pd.DataFrame(Y_test2_pred).to_csv('GNB-DS2.csv', header = None)

# Base-DT-DS1
a baseline Decision Tree using entropy as decision criterion and using default values values for the rest of the parameters.

# Base-DT-DS2

# Best-DT
a better performing Decision Tree found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* splitting criterion: gini and entropy
* maximum depth of the tree: 10 and no maximum
* minimum number of samples to split an internal node: experiment with values of your choice
* minimum impurity decrease: experiment with values of your choice
* class weight: None and balanced

# Perceptron
 a Perceptron, with default parameter values

#### Training the Perceptron model on Training Set

In [76]:
from sklearn.linear_model import Perceptron
import numpy as np
import pandas as pd

ds = input('Choose Data Set (1 or 2):')

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_"+ds+".csv", header=None)
dataset_val = pd.read_csv("dataset/val_"+ds+".csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_"+ds+".csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_"+ds+".csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1]

#train model
perClass = Perceptron()
perClass.fit(X_train, Y_train)

Choose Data Set (1 or 2):1


Perceptron()

#### Predict using Validate set

In [77]:
Y_val_pred = perClass.predict(X_val)

#### Predict using Test set

In [78]:
Y_test_pred = perClass.predict(X_test)

#### Confusion Matrix

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_test_pred)
print(cm)
accuracy_score(Y_test, Y_test_pred)

pd.DataFrame('predicted class': Y_test_pred).to_csv('PER-DS'+ds+'.csv', header = None)

SyntaxError: invalid syntax (<ipython-input-80-1051bc18f109>, line 6)

#### Output

# Base-MLP
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent