<a href="https://colab.research.google.com/github/AvkashSharma/COMP472/blob/master/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example Heading 1

## Example Heading 1.1

In [2]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
%matplotlib inline

print('testing jupyter')

testing jupyter


# GNB-DS1
Gaussian Naive Bayes Classifier, with default parameter values

# GNB-DS2
Gaussian Naive Bayes Classifier, with default parameter values

## GNB-DS1

### Importing Libraries

In [4]:
import numpy as np
import pandas as pd

### Importing and Splitting the Dataset

In [19]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_1,Y_training_1)

GaussianNB(priors=None, var_smoothing=1e-09)

### Sample prediction using X_Validate_1

In [7]:
Y_validate1_pred = classifier.predict(X_validate_1)

### Applying Classifier on Test set

In [8]:
Y_test1_pred = classifier.predict(X_test1)

### Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
accuracy_score(Y_test1, Y_test1_pred)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

0.6875

### Output file containing output classification

In [35]:
pd.DataFrame(Y_test1_pred).to_csv('GNB-DS1.csv', header = None)

## GNB-DS2

### Importing and splitting the Dataset

In [29]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test1_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test1_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train1.iloc[:, :-1].values
Y_training_2 = dataset_train1.iloc[:, -1].values
X_validate_2 = dataset_validate1.iloc[:, :-1].values
Y_validate_2 = dataset_validate1.iloc[:, -1].values
X_test2 = dataset_test1_no_label_2.iloc[:, ].values
Y_test2 = dataset_test1_with_label_2.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [30]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_2,Y_training_2)

GaussianNB(priors=None, var_smoothing=1e-09)

### Sample prediction using X_Validate_2

In [31]:
Y_validate2_pred = classifier.predict(X_validate_2)
print(np.concatenate((Y_validate2_pred.reshape(len(Y_validate2_pred),1), Y_validate_2.reshape(len(Y_validate_2),1)),1))

[[ 1  1]
 [17 17]
 [22 12]
 [ 1 12]
 [ 1  1]
 [16 16]
 [17 17]
 [25 25]
 [14 14]
 [ 9  9]
 [ 3  3]
 [ 4  4]
 [22 21]
 [12 17]
 [25 25]
 [17 10]
 [16 18]
 [15 15]
 [11 11]
 [25 15]
 [ 5  5]
 [ 8  8]
 [19 19]
 [21 21]
 [24 24]
 [12 22]
 [15 15]
 [18 18]
 [14 20]
 [ 4  4]
 [15 15]
 [20 20]
 [20 20]
 [17  0]
 [24 24]
 [17 17]
 [10 10]
 [13 13]
 [ 8  8]
 [23 23]
 [ 3  3]
 [ 8 19]
 [18 18]
 [20 20]
 [17  7]
 [ 1  9]
 [25 25]
 [22 22]
 [ 8  8]
 [ 2  2]
 [10 10]
 [21 23]
 [13 12]
 [ 0  7]
 [16 16]
 [12  9]
 [ 2  2]
 [ 6  6]
 [ 3  3]
 [14 14]
 [11 11]
 [12  6]
 [ 3  3]
 [13 21]
 [12 23]
 [14 14]
 [ 1 17]
 [16  9]
 [22 22]
 [11 11]
 [10 10]
 [17  8]
 [ 3  3]
 [ 1  4]
 [ 1  7]
 [18 18]
 [ 8  8]
 [ 4  2]
 [25 25]
 [14 14]
 [ 1 12]
 [12 20]
 [ 5 19]
 [25 25]
 [ 7  7]
 [12  6]
 [17  0]
 [18 18]
 [ 3 14]
 [12 12]
 [19 19]
 [ 0 10]
 [23 23]
 [ 5  5]
 [25 25]
 [12 16]
 [ 2  2]
 [12  0]
 [21 21]
 [25 25]
 [16  6]
 [16 14]
 [12 13]
 [13 13]
 [ 7  7]
 [15 13]
 [12 13]
 [ 9  9]
 [ 0 13]
 [13 13]
 [ 5  5]
 

### Applying Classifier on Test sets

In [32]:
Y_test2_pred = classifier.predict(X_test2)

### Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test2, Y_test2_pred)
print(cm)
accuracy_score(Y_test2, Y_test2_pred)

NameError: name 'Y_test2' is not defined

### Output file containing output classification

In [36]:
pd.DataFrame(Y_test2_pred).to_csv('GNB-DS2.csv', header = None)

# -------------------Base-DT-DS1-------------------
a baseline Decision Tree using entropy as decision criterion and using default values values for the rest of the parameters

## Importing and Splitting the dataset

In [184]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training the DT model on the Training set

In [185]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_training_1,Y_training_1)

DecisionTreeClassifier(criterion='entropy')

# -------------------Base-DT-DS2-------------------

## Importing and Splitting the dataset

In [190]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training the DT model on the Training set

In [191]:
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_training_2,Y_training_2)

DecisionTreeClassifier(criterion='entropy')

# -------------------Best-DT-------------------
a better performing Decision Tree found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* splitting criterion: gini and entropy
* maximum depth of the tree: 10 and no maximum
* minimum number of samples to split an internal node: experiment with values of your choice
* minimum impurity decrease: experiment with values of your choice
* class weight: None and balanced

## Importing and Splitting the dataset

In [184]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training the DT model on the Training set

In [196]:
from sklearn.tree import export_graphviz
from sklearn.model_selection   import GridSearchCV, cross_val_score
from sklearn.model_selection import cross_val_score


tree_para = {'criterion':['gini','entropy'],'max_depth':[10],'min_impurity_decrease':[0,1.0,2.0,3.0,4.0,5.0],'min_samples_split':[2,4,6,8]}
classifier_Best_DT = GridSearchCV(DecisionTreeClassifier(), tree_para)
classifier_Best_DT.fit(X_training_1, Y_training_1)
classifier_Best_DT.best_estimator_

classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_1,Y_training_1)


DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)

## Sample prediction using X_Validate_1

In [198]:
validate1_pred = classifier.predict(X_validate_1)

## Applying Classifier on Test set

In [199]:
Y_test1_pred = classifier.predict(X_test1)

## Confusion Matrix and Classification Report

In [17]:
from sklearn.metrics import classification_report

cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
cr = classification_report(Y_test1, Y_test1_pred)
print(cr)

[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

C:\Users\nnadaraj\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Output file containing output classification

In [201]:
pf = pd.DataFrame(cm)
pf.to_csv('Best-DT-DS1.csv', header = None, index = None)

# -------------------Best-DT2-------------------

## Importing and Splitting the dataset

In [19]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training the DT model on the Training set

In [202]:
from sklearn.tree import export_graphviz
from sklearn.model_selection   import GridSearchCV, cross_val_score
from sklearn.model_selection import cross_val_score


tree_para2 = {'criterion':['gini','entropy'],'max_depth':[10],'min_impurity_decrease':[0,1.0,2.0,3.0,4.0,5.0],'min_samples_split':[2,4,6,8]}
classifier_Best_DT2 = GridSearchCV(DecisionTreeClassifier(), tree_para2)
classifier_Best_DT2.fit(X_training_2, Y_training_2)
classifier_Best_DT2.best_estimator_

classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_2,Y_training_2)


DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)

## Sample prediction using X_Validate_2

In [204]:
validate2_pred = classifier.predict(X_validate_2)

## Applying Classifier on Test set

In [205]:
Y_test2_pred = classifier.predict(X_test2)

## Confusion Matrix and Classification Report

In [20]:
from sklearn.metrics import classification_report

cm2 = confusion_matrix(Y_test2, Y_test2_pred)
print(cm2)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cr2)

NameError: name 'Y_test2_pred' is not defined

## Output file containing output classification

In [207]:
pf = pd.DataFrame(cm2)
pf.to_csv('Best-DT-DS2.csv', header = None, index = None)

# Perceptron
 a Perceptron, with default parameter values

#### Training the Perceptron model on Training Set

In [76]:
from sklearn.linear_model import Perceptron
import numpy as np
import pandas as pd

ds = input('Choose Data Set (1 or 2):')

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_"+ds+".csv", header=None)
dataset_val = pd.read_csv("dataset/val_"+ds+".csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_"+ds+".csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_"+ds+".csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1]

#train model
perClass = Perceptron()
perClass.fit(X_train, Y_train)

Choose Data Set (1 or 2):1


Perceptron()

#### Predict using Validate set

In [77]:
Y_val_pred = perClass.predict(X_val)

#### Predict using Test set

In [78]:
Y_test_pred = perClass.predict(X_test)

#### Confusion Matrix

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_test_pred)
print(cm)
accuracy_score(Y_test, Y_test_pred)

pd.DataFrame('predicted class': Y_test_pred).to_csv('PER-DS'+ds+'.csv', header = None)

SyntaxError: invalid syntax (<ipython-input-80-1051bc18f109>, line 6)

#### Output

# Base-MLP-DS1
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

## Importing and Splitting the dataset

In [5]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training the DT model on the Training set

In [9]:
from sklearn.neural_network import MLPClassifier 

classifier = MLPClassifier(hidden_layer_sizes=(100), activation='logistic', solver='sgd')
classifier.fit(X_training_1,Y_training_1)

C:\Users\nnadaraj\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', hidden_layer_sizes=100, solver='sgd')

## Sample prediction using X_Validate_1

In [11]:
validate1_pred = classifier.predict(X_validate_1)

## Applying Classifier on Test set

In [13]:
Y_test1_pred = classifier.predict(X_test1)

## Confusion Matrix and Classification Report

In [22]:
from sklearn.metrics import classification_report

print(np.concatenate((Y_test1_pred.reshape(len(Y_test1_pred),1), Y_test1_pred.reshape(len(Y_test1_pred),1)),1))
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
cr = classification_report(Y_test1, Y_test1_pred)
print(cr)

[[ 2  2]
 [13 13]
 [17 17]
 [ 2  2]
 [17 17]
 [17 17]
 [11 11]
 [17 17]
 [22 22]
 [11 11]
 [ 6  6]
 [ 9  9]
 [ 2  2]
 [ 8  8]
 [11 11]
 [10 10]
 [13 13]
 [ 8  8]
 [ 2  2]
 [ 0  0]
 [ 6  6]
 [ 0  0]
 [ 9  9]
 [17 17]
 [ 8  8]
 [17 17]
 [10 10]
 [ 8  8]
 [17 17]
 [ 6  6]
 [17 17]
 [17 17]
 [10 10]
 [16 16]
 [10 10]
 [10 10]
 [ 6  6]
 [ 8  8]
 [15 15]
 [12 12]
 [14 14]
 [10 10]
 [13 13]
 [13 13]
 [10 10]
 [17 17]
 [10 10]
 [14 14]
 [15 15]
 [ 0  0]
 [ 7  7]
 [ 8  8]
 [11 11]
 [10 10]
 [14 14]
 [14 14]
 [ 0  0]
 [ 9  9]
 [17 17]
 [14 14]
 [10 10]
 [11 11]
 [11 11]
 [11 11]
 [17 17]
 [ 6  6]
 [ 6  6]
 [11 11]
 [12 12]
 [ 6  6]
 [13 13]
 [11 11]
 [13 13]
 [ 8  8]
 [22 22]
 [ 9  9]
 [10 10]
 [17 17]
 [ 6  6]
 [ 8  8]]
[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

## Output file containing output classification

In [23]:
pf = pd.DataFrame(cm)
pf.to_csv('Base-MLP-DS1.csv', header = None, index = None)

# Base-MLP-DS2
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

## Importing and Splitting the dataset

In [24]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training the DT model on the Training set

In [25]:
from sklearn.neural_network import MLPClassifier 

classifier = MLPClassifier(hidden_layer_sizes=(100), activation='logistic', solver='sgd')
classifier.fit(X_training_2,Y_training_2)


C:\Users\nnadaraj\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', hidden_layer_sizes=100, solver='sgd')

## Sample prediction using X_Validate_2

In [27]:
validate2_pred = classifier.predict(X_validate_2)

## Applying Classifier on Test set

In [28]:
Y_test2_pred = classifier.predict(X_test2)

## Confusion Matrix and Classification Report

In [29]:
from sklearn.metrics import classification_report

print(np.concatenate((Y_test2_pred.reshape(len(Y_test2_pred),1), Y_test2_pred.reshape(len(Y_test2_pred),1)),1))
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
print(cm2)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cr2)

[[9 9]
 [0 0]
 [4 4]
 ...
 [9 9]
 [6 6]
 [5 5]]
[[ 46   3   1   0   0   2   0   0   1   2]
 [  2 120   0   1   0   1   0   0   1   0]
 [  0   0   6   0   0   1   0   0   7   1]
 [  1   1   0  11   1   1   0   0   0   0]
 [  5   1   0   0  29   2   0   0   3  10]
 [  0   0   0   0   1  50   0   0   0   4]
 [  2   4   1   0   1   0   5   0   1   1]
 [  0   0   0   0   0   0   0  15   0   0]
 [  1   1   0   0   0   0   0   0  44   4]
 [  2   0   0   0   7   5   0   0   1 110]]
              precision    recall  f1-score   support

           0       0.78      0.84      0.81        55
           1       0.92      0.96      0.94       125
           2       0.75      0.40      0.52        15
           3       0.92      0.73      0.81        15
           4       0.74      0.58      0.65        50
           5       0.81      0.91      0.85        55
           6       1.00      0.33      0.50        15
           7       1.00      1.00      1.00        15
           8       0.76      0.88 

## Output file containing output classification

In [30]:
pf = pd.DataFrame(cm2)
pf.to_csv('Base-MLP-DS2.csv', header = None, index = None)

# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent