<a href="https://colab.research.google.com/github/AvkashSharma/COMP472/blob/master/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example Heading 1

## Example Heading 1.1

In [ ]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
%matplotlib inline

print('testing jupyter')

# GNB-DS1
Gaussian Naive Bayes Classifier, with default parameter values

# GNB-DS2
Gaussian Naive Bayes Classifier, with default parameter values

## GNB-DS1

### Importing Libraries

In [ ]:
import numpy as np
import pandas as pd

### Importing and Splitting the Dataset

In [ ]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_1,Y_training_1)

### Sample prediction using X_Validate_1

In [ ]:
Y_validate1_pred = classifier.predict(X_validate_1)

### Applying Classifier on Test set

In [ ]:
Y_test1_pred = classifier.predict(X_test1)

### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
accuracy_score(Y_test1, Y_test1_pred)

### Output file containing output classification

In [ ]:
pd.DataFrame(Y_test1_pred).to_csv('GNB-DS1.csv', header = None)

## GNB-DS2

### Importing and splitting the Dataset

In [ ]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test1_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test1_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train1.iloc[:, :-1].values
Y_training_2 = dataset_train1.iloc[:, -1].values
X_validate_2 = dataset_validate1.iloc[:, :-1].values
Y_validate_2 = dataset_validate1.iloc[:, -1].values
X_test2 = dataset_test1_no_label_2.iloc[:, ].values
Y_test2 = dataset_test1_with_label_2.iloc[:,-1]

### Training the Gaussian Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_training_2,Y_training_2)

### Sample prediction using X_Validate_2

In [ ]:
Y_validate2_pred = classifier.predict(X_validate_2)
print(np.concatenate((Y_validate2_pred.reshape(len(Y_validate2_pred),1), Y_validate_2.reshape(len(Y_validate_2),1)),1))

### Applying Classifier on Test sets

In [ ]:
Y_test2_pred = classifier.predict(X_test2)

### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test2, Y_test2_pred)
print(cm)
accuracy_score(Y_test2, Y_test2_pred)

### Output file containing output classification

In [ ]:
pd.DataFrame(Y_test2_pred).to_csv('GNB-DS2.csv', header = None)

# -------------------Base-DT-DS1-------------------
a baseline Decision Tree using entropy as decision criterion and using default values values for the rest of the parameters

## Importing and Splitting the dataset

In [ ]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training the DT model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_training_1,Y_training_1)

# -------------------Base-DT-DS2-------------------

## Importing and Splitting the dataset

In [ ]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training the DT model on the Training set

In [ ]:
classifier.fit(X_training_2,Y_training_2)

# -------------------Best-DT-------------------
a better performing Decision Tree found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* splitting criterion: gini and entropy
* maximum depth of the tree: 10 and no maximum
* minimum number of samples to split an internal node: experiment with values of your choice
* minimum impurity decrease: experiment with values of your choice
* class weight: None and balanced

## Training the DT model on the Training set

In [ ]:
from sklearn.tree import export_graphviz
from sklearn.model_selection   import GridSearchCV, cross_val_score
from sklearn.model_selection import cross_val_score


tree_para = {'criterion':['gini','entropy'],'max_depth':[10],'min_impurity_decrease':[0,1.0,2.0,3.0,4.0,5.0],'min_samples_split':[2,4,6,8]}
classifier_Best_DT = GridSearchCV(DecisionTreeClassifier(), tree_para)
classifier_Best_DT.fit(X_training_1, Y_training_1)
classifier_Best_DT.best_estimator_

classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_1,Y_training_1)


In [ ]:
classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_1,Y_training_1)

## Sample prediction using X_Validate_1

In [ ]:
validate1_pred = classifier.predict(X_validate_1)

## Applying Classifier on Test set

In [ ]:
Y_test1_pred = classifier.predict(X_test1)

## Confusion Matrix and Classification Report

In [ ]:
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
cr = classification_report(Y_test1, Y_test1_pred)
print(cr)

## Output file containing output classification

In [ ]:
pf = pd.DataFrame(cm)
pf.to_csv('Best-DT-DS1.csv', header = None, index = None)

# -------------------Best-DT2-------------------

## Training the DT model on the Training set

In [ ]:
from sklearn.tree import export_graphviz
from sklearn.model_selection   import GridSearchCV, cross_val_score
from sklearn.model_selection import cross_val_score


tree_para2 = {'criterion':['gini','entropy'],'max_depth':[10],'min_impurity_decrease':[0,1.0,2.0,3.0,4.0,5.0],'min_samples_split':[2,4,6,8]}
classifier_Best_DT2 = GridSearchCV(DecisionTreeClassifier(), tree_para2)
classifier_Best_DT2.fit(X_training_2, Y_training_2)
classifier_Best_DT2.best_estimator_

classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_2,Y_training_2)


In [ ]:
classifier = DecisionTreeClassifier(criterion='entropy', max_depth=10,
                       min_impurity_decrease=0, min_samples_split=4)
classifier.fit(X_training_2,Y_training_2)

## Sample prediction using X_Validate_2

In [ ]:
validate2_pred = classifier.predict(X_validate_2)

## Applying Classifier on Test set

In [ ]:
Y_test2_pred = classifier.predict(X_test2)

## Confusion Matrix and Classification Report

In [ ]:
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
print(cm2)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cr2)

## Output file containing output classification

In [ ]:
pf = pd.DataFrame(cm2)
pf.to_csv('Best-DT-DS2.csv', header = None, index = None)

# Perceptron
 a Perceptron, with default parameter values

#### Training the Perceptron model on Training Set

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np
import pandas as pd

ds = input('Choose Data Set (1 or 2):')

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_"+ds+".csv", header=None)
dataset_val = pd.read_csv("dataset/val_"+ds+".csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_"+ds+".csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_"+ds+".csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1]

#train model
perClass = Perceptron()
perClass.fit(X_train, Y_train)

#### Predict using Validate set

In [ ]:
Y_val_pred = perClass.predict(X_val)

#### Predict using Test set

In [ ]:
Y_test_pred = perClass.predict(X_test)

#### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test, Y_test_pred)
# cm = confusion_matrix(Y_val, Y_val_pred)
print(cm)
cr = classification_report(Y_test, Y_test_pred)
# cr = classification_report(Y_val, Y_val_pred)
print(cr)

pd.DataFrame(Y_test_pred).to_csv('PER-DS'+ds+'.csv', header = None)

# Base-MLP
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent

## Training the Perceptron model on Training Set

## TOC:
* [First Bullet Header](#first-bullet)
* [Second Bullet Header](#second-bullet)

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

ds = input('Choose Data Set (1 or 2):')

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_"+ds+".csv", header=None)
dataset_val = pd.read_csv("dataset/val_"+ds+".csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_"+ds+".csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_"+ds+".csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1]

param_grid = {
    'hidden_layer_sizes': [(30,50,), (10,10,10,)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['adam', 'sgd']
}


classifier = GridSearchCV(MLPClassifier(), param_grid)
classifier.fit(X_train, Y_train)

Choose Data Set (1 or 2):1


GridSearchCV(estimator=MLPClassifier(),
             param_grid={'activation': ['logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [(30, 50), (10, 10, 10)],
                         'solver': ['adam', 'sgd']})

In [2]:
Y_val_pred = classifier.predict(X_val)

In [3]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val, Y_val_pred)
print(cm)
cr = classification_report(Y_val, Y_val_pred)
print(cr)

pd.DataFrame(Y_val_pred).to_csv('BEST-MLP-DS'+ds+'.csv', header = None)

[[ 7  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  1  0  0  0  0  0  0  0
   0  0]
 [ 0  5  0  0  0  1  0  0  0  1  0  0  0  0  0  0  1  0  0  0  0  0  0  0
   1  0]
 [ 0  0  8  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  5  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  6  0  0  0  0  2  0  0  1  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 1  0  0  0  0  0  0  0  2  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  9  0  0  1  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0

In [4]:
Y_test_pred = classifier.predict(X_test)

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test, Y_test_pred)
print(cm)
cr = classification_report(Y_test, Y_test_pred)
print(cr)

pd.DataFrame(Y_test_pred).to_csv('BEST-MLP-DS'+ds+'.csv', header = None)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 