# Base-DT
A baseline Decision Tree using entropy as decision criterion and using default values values
for the rest of the parameters.

# Base-DT-DS1

#### Import libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#### Import data

In [2]:
# Import dataset according to selection
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_val1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label = pd.read_csv("dataset/test_with_label_1.csv",header=None)

# X = data, Y = target 
X_train1 = dataset_train1.iloc[:, :-1].values
Y_train1 = dataset_train1.iloc[:, -1].values
X_val1 = dataset_val1.iloc[:, :-1].values
Y_val1 = dataset_val1.iloc[:, -1].values
X_test1 = dataset_test1.iloc[:, ].values
Y_test1 = dataset_test1_with_label.iloc[:,-1]

#### Train Model

In [3]:
classifier1 = DecisionTreeClassifier(criterion='entropy')
classifier1.fit(X_train1,Y_train1)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

#### VALIDATE - Predict using Validation Data

In [4]:
Y_val1_pred = classifier1.predict(X_val1)

#### VALIDATE - Output - Confusion matrix validate Set

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm_val = confusion_matrix(Y_val1, Y_val1_pred)
cr_val = classification_report(Y_val1, Y_val1_pred)
print(Y_val1_pred)
print(cm_val)
print(cr_val)

[ 9 17 12 12  1 24 15  5  9 17  9 25 22 15  9 24  2  8 20 15 19  1 25 23
 24 12 15 18 20 14 15 20 20  0 23  1 10 22  8 22  9 19 18 20  8 19 14 22
 21  2 10 23 12  7 18 11  2  0 20 14 11  7 25 13 13 14 16  4 22 11  0 17
  3  4  7  6  3 19 25  3 12 20  9  5  7  6  0  4 14  8 12 10 25  5  9 17
  2  0 25 10 14 20 10 13  0 24 25 25 17 13  2 18 11 14  0 21 20 18  4 25
  0  5 11 15 15 11 16  7 25 12 20 16 17  4 15 19 22 10 23 13 18  8  6  9
  9  6  2  4  3 20 22  4 12 25 10 25  4  0 20 10 21  5  0  7 23  2 11 12
 13  6 19 22 11 19 14 15 20 19  0 18  1 17  4  5 12 19 11  0  6  0 12  8
 22  4 17 10  2 10 16 19  8  9 23  0 10  5  9  2  2 23 18 20 10 14 21  2
  8  3 14 21  0 24  2  7 24  1 25  9 12  6  3 11 21 10 24 24  2  8  5]
[[7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0]
 [0 2 0 0 2 1 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 3 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 3 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 

#### TEST - Predict using Test Set

In [7]:
Y_test1_pred = classifier1.predict(X_test1)

#### TEST - Output - Confusion matrix Test Set

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test1, Y_test1_pred)
cr = classification_report(Y_test1, Y_test1_pred)
print(cm)
print(cr)

# output result 
pd.DataFrame(Y_test1_pred).to_csv('output/Base-DT-DS1.csv', header = None)
# append report
with open('output/Base-DT-DS1.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr)

[[3 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 

# Base-DT-DS2

#### Import libraries

In [9]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#### Import data

In [10]:
# Import dataset according to selection
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_val2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label = pd.read_csv("dataset/test_with_label_2.csv",header=None)

# X = data, Y = target 
X_train2 = dataset_train2.iloc[:, :-1].values
Y_train2 = dataset_train2.iloc[:, -1].values
X_val2 = dataset_val2.iloc[:, :-1].values
Y_val2 = dataset_val2.iloc[:, -1].values
X_test2 = dataset_test2.iloc[:, ].values
Y_test2 = dataset_test2_with_label.iloc[:,-1]

#### Train Model

In [11]:
classifier2 = DecisionTreeClassifier(criterion='entropy')
classifier2.fit(X_train2,Y_train2)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

#### VALIDATE - Predict using Validation Data

In [12]:
Y_val2_pred = classifier2.predict(X_val2)

#### VALIDATE - Output - Confusion matrix validate Set

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm_val2 = confusion_matrix(Y_val2, Y_val2_pred)
cr_val2 = classification_report(Y_val2, Y_val2_pred)
print(Y_val2_pred)
print(cm_val2)
print(cr_val2)

[9 7 1 ... 0 0 1]
[[123   8   2   1  19   2   2   1   0   7]
 [  5 345   0  13   5   3   1   1   0   2]
 [  3   2  27   0   1   2   0   0   4   6]
 [  1  13   0  26   1   1   0   2   0   1]
 [ 13   2   1   2  84  14   2   0   7  25]
 [  2   3   2   5   7 120   1   0   1  24]
 [  1   1   1   0   3   0  34   1   2   2]
 [  1   2   0   0   1   3   1  36   0   1]
 [  6   9   1   0   3   0   2   0 121   8]
 [  5   3  12   0  30  24   4   1   8 288]]
              precision    recall  f1-score   support

           0       0.77      0.75      0.76       165
           1       0.89      0.92      0.90       375
           2       0.59      0.60      0.59        45
           3       0.55      0.58      0.57        45
           4       0.55      0.56      0.55       150
           5       0.71      0.73      0.72       165
           6       0.72      0.76      0.74        45
           7       0.86      0.80      0.83        45
           8       0.85      0.81      0.83       150
          

#### TEST - Predict using Test Set

In [14]:
Y_test2_pred = classifier2.predict(X_test2)

#### TEST - Output - Confusion matrix Test Set

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cm2)
print(cr2)

# output result 
pd.DataFrame(Y_test2_pred).to_csv('output/Base-DT-DS2.csv', header = None)
# append report
with open('output/Base-DT-DS2.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm2).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr2)

[[ 43   3   2   0   6   0   0   0   0   1]
 [  0 113   0   4   4   2   0   0   2   0]
 [  1   0   7   0   1   1   0   0   3   2]
 [  0   4   0  10   0   1   0   0   0   0]
 [  2   2   0   1  26   2   1   0   1  15]
 [  0   0   0   1   4  41   0   0   0   9]
 [  1   0   2   0   0   1   7   0   2   2]
 [  0   1   0   0   0   0   0  13   1   0]
 [  5   1   0   0   1   0   0   0  42   1]
 [  2   2   2   0   8   7   0   0   1 103]]
              precision    recall  f1-score   support

           0       0.80      0.78      0.79        55
           1       0.90      0.90      0.90       125
           2       0.54      0.47      0.50        15
           3       0.62      0.67      0.65        15
           4       0.52      0.52      0.52        50
           5       0.75      0.75      0.75        55
           6       0.88      0.47      0.61        15
           7       1.00      0.87      0.93        15
           8       0.81      0.84      0.82        50
           9       0.77     