# Base-DT
A baseline Decision Tree using entropy as decision criterion and using default values values
for the rest of the parameters.

# Base-DT-DS1

#### Import libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#### Import data

In [2]:
# Import dataset according to selection
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_val1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label = pd.read_csv("dataset/test_with_label_1.csv",header=None)

# X = data, Y = target 
X_train1 = dataset_train1.iloc[:, :-1].values
Y_train1 = dataset_train1.iloc[:, -1].values
X_val1 = dataset_val1.iloc[:, :-1].values
Y_val1 = dataset_val1.iloc[:, -1].values
X_test1 = dataset_test1.iloc[:, ].values
Y_test1 = dataset_test1_with_label.iloc[:,-1]

#### Train Model

In [4]:
classifier1 = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier1.fit(X_train1,Y_train1)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

#### VALIDATE - Predict using Validation Data

In [5]:
Y_val1_pred = classifier1.predict(X_val1)

#### VALIDATE - Output - Confusion matrix validate Set

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm_val = confusion_matrix(Y_val1, Y_val1_pred)
cr_val = classification_report(Y_val1, Y_val1_pred)
print(Y_val1_pred)
print(cm_val)
print(cr_val)

[ 9 17 10 12  1 13 15  9 18 15  9 25 22 15  9 24  6  8 20 15 19  9 25 23
 24 12 15 18 20 15 15 20 20  0  0  1 10 22  8 22  9 19 18 20  8 19 14 22
 21  2 10 23 12  7 16 11  2  0 20 14 11  7 25 13 13  6 25  4 22 11  1 17
  3  4  7  6  3  6 25  3 12 20  9  5  7  6  0 19 14  8 18 10 25  5  9  5
  2  0  6 10  6 20 10 13  0 24  6 16 23 13  2 18 11 14 23 21 20  3  6 25
  0 15 11 15 15 11 14  7 25 12 20 16 17  4 15 19 22 10 23 13 10  8 18  3
 14  6  6  4  3 20 22 25 12 25 10  1  4  0 20 10 21  5  0 12 23  2 11 13
 10  6  5 22 11 25 16 15 20 19  0 18 11  0  4  5 24  6 11 24 16  0 13  8
 22  4  9 10  2 10 16 19  8  3 23  0 10  5  9  2  2  0 18 20 10 14 21  2
  8  3 15 21  0 24  2  7 24 25 25  9 19 25  3 11 21 10 13 24  2  8  5]
[[9 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2]
 [0 0 8 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 3 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 

#### TEST - Predict using Test Set

In [8]:
Y_test1_pred = classifier1.predict(X_test1)

#### TEST - Output - Confusion matrix Test Set

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test1, Y_test1_pred)
cr = classification_report(Y_test1, Y_test1_pred)
print(cm)
print(cr)

# output result 
pd.DataFrame(Y_test1_pred).to_csv('output/Base-DT-DS1.csv', header = None)
# append report
with open('output/Base-DT-DS1.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr)

[[3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 1 0 

# Base-DT-DS2

#### Import libraries

In [11]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#### Import data

In [12]:
# Import dataset according to selection
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_val2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label = pd.read_csv("dataset/test_with_label_2.csv",header=None)

# X = data, Y = target 
X_train2 = dataset_train2.iloc[:, :-1].values
Y_train2 = dataset_train2.iloc[:, -1].values
X_val2 = dataset_val2.iloc[:, :-1].values
Y_val2 = dataset_val2.iloc[:, -1].values
X_test2 = dataset_test2.iloc[:, ].values
Y_test2 = dataset_test2_with_label.iloc[:,-1]

#### Train Model

In [13]:
classifier2 = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier2.fit(X_train2,Y_train2)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

#### VALIDATE - Predict using Validation Data

In [14]:
Y_val2_pred = classifier2.predict(X_val2)

#### VALIDATE - Output - Confusion matrix validate Set

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm_val2 = confusion_matrix(Y_val2, Y_val2_pred)
cr_val2 = classification_report(Y_val2, Y_val2_pred)
print(Y_val2_pred)
print(cm_val2)
print(cr_val2)

[9 7 1 ... 0 0 1]
[[130   9   2   2  10   2   2   1   0   7]
 [  6 339   0  21   2   4   1   0   0   2]
 [  0   3  27   0   3   2   0   0   4   6]
 [  0  15   0  25   1   2   1   0   0   1]
 [ 12   6   2   1  79  14   2   0   5  29]
 [  4   2   5   3   4 124   1   0   2  20]
 [  2   1   0   0   3   0  30   0   2   7]
 [  1   1   0   0   1   2   1  37   0   2]
 [  5   7   2   1   5   1   1   0 119   9]
 [  7   3   9   3  26  31   2   0  10 284]]
              precision    recall  f1-score   support

           0       0.78      0.79      0.78       165
           1       0.88      0.90      0.89       375
           2       0.57      0.60      0.59        45
           3       0.45      0.56      0.50        45
           4       0.59      0.53      0.56       150
           5       0.68      0.75      0.71       165
           6       0.73      0.67      0.70        45
           7       0.97      0.82      0.89        45
           8       0.84      0.79      0.82       150
          

#### TEST - Predict using Test Set

In [16]:
Y_test2_pred = classifier2.predict(X_test2)

#### TEST - Output - Confusion matrix Test Set

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cm2)
print(cr2)

# output result 
pd.DataFrame(Y_test2_pred).to_csv('output/Base-DT-DS2.csv', header = None)
# append report
with open('output/Base-DT-DS2.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm2).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr2)

[[ 47   1   1   0   5   0   0   0   0   1]
 [  1 116   0   5   0   2   0   0   1   0]
 [  1   0   6   0   2   1   0   0   2   3]
 [  0   4   0   8   1   2   0   0   0   0]
 [  3   2   1   1  27   1   1   0   1  13]
 [  0   0   0   1   6  41   0   0   1   6]
 [  1   0   2   0   1   1   7   0   2   1]
 [  0   2   0   0   0   0   0  12   1   0]
 [  3   1   0   0   0   0   1   0  43   2]
 [  2   1   2   0  10  10   0   0   3  97]]
              precision    recall  f1-score   support

           0       0.81      0.85      0.83        55
           1       0.91      0.93      0.92       125
           2       0.50      0.40      0.44        15
           3       0.53      0.53      0.53        15
           4       0.52      0.54      0.53        50
           5       0.71      0.75      0.73        55
           6       0.78      0.47      0.58        15
           7       1.00      0.80      0.89        15
           8       0.80      0.86      0.83        50
           9       0.79     