# Base-MLP-DS1
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing and Splitting the dataset

In [2]:
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_validate1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1_no_label_1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label_1 = pd.read_csv("dataset/test_with_label_1.csv",header=None)
X_training_1 = dataset_train1.iloc[:, :-1].values
Y_training_1 = dataset_train1.iloc[:, -1].values
X_validate_1 = dataset_validate1.iloc[:, :-1].values
Y_validate_1 = dataset_validate1.iloc[:, -1].values
X_test1 = dataset_test1_no_label_1.iloc[:, ].values
Y_test1 = dataset_test1_with_label_1.iloc[:,-1]

## Training Using Training set

In [3]:
from sklearn.neural_network import MLPClassifier
import warnings
warnings.filterwarnings("ignore")

classifier = MLPClassifier(hidden_layer_sizes=(100), activation='logistic', solver='sgd')
classifier.fit(X_training_1,Y_training_1)


MLPClassifier(activation='logistic', hidden_layer_sizes=100, solver='sgd')

## Validate - Predict Using Validate Set

In [4]:
Y_validate1_pred = classifier.predict(X_validate_1)

## Validate - Output - Confusion Matrix and Classification Report

In [5]:
from sklearn.metrics import confusion_matrix, classification_report
import csv

print(Y_validate1_pred)
cm = confusion_matrix(Y_validate_1, Y_validate1_pred)
print(cm)
cr = classification_report(Y_validate_1, Y_validate1_pred)
print(cr)

[17 17 13 13 17 16 17  8 14  8 15  2 13 15  8 13 11  8 11 15  8  8  8 13
 17  0 10  2 14  8 10 13 11  0  9 17 10 13  8 17 14  8  6 13  8  9  8 13
  8 14 10 17 12  7 16 16  2  6 11  2 11  6 17 13 17 14 10  9 11 11 10  8
  9 15  7  6  8  2  8 14 12  6 17 15  7 14 17  9 14  0  8 10 10 15  8  2
  2  0 13 10 14  6  0 13 13 10 17  9 13 13 10  6 11 14 13 21 10 17  6 10
 17  8 11 17 15 11 14  7  8 14 11 16 17  8 16  8 22 17 17 12  0  8 13 17
  9  6  6 14 15  6 22  0 12 10 10  9  8  8 14 10 13 15  0 13 17  6  2  2
 13  8 15 22  6 17 16 15 11  8 10  2 14 13 10 17  8  2 11 22  6  0  2  8
 11 15  9 11  2 10  2 14  8 17 13  0  7  2  8  2  2 13 17 11 10 14 11  6
  8  9  6  8  0 17  2  7 12  2 17 15 12  2 15 11 17 10 13 17  2  8 15]
[[ 6  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  2  0  0  0  0  0  0
   0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0  0  0  0  2  0  0  5  0  0  0  0  0  0
   0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0 

## Test - Predict Using Test Set

In [6]:
Y_test1_pred = classifier.predict(X_test1)

## Test - Output - Confusion Matrix and Classification Report

In [7]:
print(Y_test1_pred)
cm = confusion_matrix(Y_test1, Y_test1_pred)
print(cm)
cr = classification_report(Y_test1, Y_test1_pred)
print(cr)

pd.DataFrame(Y_test1_pred).to_csv('output/Base-MLP-DS1.csv', header = None)
with open('output/Base-MLP-DS1.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr)

[ 8 13 17  2  0 17 11 17 22 11  6  9 11  8  8 10  0  8  2  0 16  0  8 17
  8 17 22  8 17  6 15 13 10 16 10 10  6  8 15  2 16 10 13 17 10 17 10 14
 17  0  7 15 11 13 14 14  0  9 17 14 12  2 11 10 17  6  6 14 12 13 13 14
 13  8 11  6 10 17  6  8]
[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 3 0 0 0 0 0 

# Base-MLP-DS2
a baseline Multi-Layered Perceptron with 1 hidden layer of100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters.

## Importing and Splitting the dataset

In [8]:
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_validate2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2_no_label_2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label_2 = pd.read_csv("dataset/test_with_label_2.csv",header=None)
X_training_2 = dataset_train2.iloc[:, :-1].values
Y_training_2 = dataset_train2.iloc[:, -1].values
X_validate_2 = dataset_validate2.iloc[:, :-1].values
Y_validate_2 = dataset_validate2.iloc[:, -1].values
X_test2 = dataset_test2_no_label_2.iloc[:, ].values
Y_test2 = dataset_test2_with_label_2.iloc[:,-1]

## Training Using Training set

In [9]:
classifier = MLPClassifier(hidden_layer_sizes=(100), activation='logistic', solver='sgd')
classifier.fit(X_training_2,Y_training_2)

MLPClassifier(activation='logistic', hidden_layer_sizes=100, solver='sgd')

## Validate - Predict Using Validate Set

In [10]:
Y_validate2_pred = classifier.predict(X_validate_2)

## Validate - Output - Confusion Matrix and Classification Report

In [11]:
print(Y_validate2_pred)
cm2 = confusion_matrix(Y_validate_2, Y_validate2_pred)
print(cm2)
cr2 = classification_report(Y_validate_2, Y_validate2_pred)
print(cr2)

[9 7 1 ... 8 0 1]
[[144   4   0   0   7   0   0   0   7   3]
 [  4 367   0   1   0   2   0   0   0   1]
 [  1   2  13   0   2   2   0   0  20   5]
 [  1   9   0  30   2   3   0   0   0   0]
 [ 13   0   1   0 100   6   0   0   4  26]
 [  0   7   0   1   4 145   0   0   1   7]
 [  0   7   0   0   3   0  31   0   1   3]
 [  1   2   0   0   0   2   0  39   0   1]
 [  4   9   0   0   5   0   1   0 127   4]
 [  2   3   1   0  15  12   0   0   1 341]]
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       165
           1       0.90      0.98      0.94       375
           2       0.87      0.29      0.43        45
           3       0.94      0.67      0.78        45
           4       0.72      0.67      0.69       150
           5       0.84      0.88      0.86       165
           6       0.97      0.69      0.81        45
           7       1.00      0.87      0.93        45
           8       0.79      0.85      0.82       150
          

## Test - Predict Using Test Set

In [12]:
Y_test2_pred = classifier.predict(X_test2)

## Test - Output - Confusion Matrix and Classification Report

In [13]:
print(Y_test2_pred)
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
print(cm2)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cr2)

pd.DataFrame(Y_test2_pred).to_csv('output/Base-MLP-DS2.csv', header = None)
with open('output/Base-MLP-DS2.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm2).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr2)

[9 0 4 5 9 1 1 3 8 9 5 1 3 9 9 1 9 9 7 1 6 1 9 7 9 8 1 1 8 8 9 8 8 9 8 1 9
 9 1 1 1 7 9 5 9 9 1 1 5 1 9 9 5 9 0 0 8 5 9 1 1 9 0 0 9 0 1 4 0 0 3 1 1 9
 5 8 9 1 0 9 7 1 0 5 0 9 9 9 7 1 8 4 1 1 5 1 9 9 0 0 4 8 8 2 4 5 8 5 5 4 1
 9 5 5 8 9 8 0 8 9 1 5 5 9 1 1 2 4 4 9 1 1 8 1 9 1 4 9 0 8 5 0 1 4 4 4 9 9
 5 1 1 5 9 1 5 0 1 5 5 3 0 8 0 1 1 1 1 1 9 0 5 9 5 0 4 1 1 0 0 5 4 1 9 9 4
 1 9 9 0 3 1 9 1 9 5 7 9 7 9 9 5 0 9 0 5 5 8 1 5 1 4 5 1 0 9 0 8 1 1 9 8 1
 9 4 9 3 8 5 8 1 9 1 4 9 1 6 5 9 8 1 2 0 9 9 1 1 5 0 9 7 9 1 1 1 9 0 9 4 1
 1 9 1 1 1 5 5 9 2 7 8 5 4 9 1 7 8 5 8 9 5 0 4 4 6 0 9 0 1 9 1 3 9 8 8 1 9
 1 0 8 5 1 5 9 5 1 1 1 7 1 3 9 9 1 9 1 8 5 9 9 7 9 1 9 9 2 5 9 0 1 9 5 1 9
 4 1 6 7 1 9 4 8 8 5 8 0 5 5 4 9 9 5 3 1 8 1 9 4 1 1 1 0 9 0 9 9 8 8 1 1 1
 9 5 1 5 1 4 1 9 8 8 1 9 1 1 1 9 4 4 9 8 9 9 0 1 5 1 2 8 2 1 1 9 0 9 8 7 8
 9 8 9 5 6 1 9 1 1 9 1 4 5 9 9 0 9 8 0 9 5 4 8 9 0 1 9 9 1 1 9 9 5 1 0 0 1
 0 9 8 8 0 9 9 4 1 9 8 0 1 0 1 9 1 8 8 9 9 4 1 8 7 8 9 8 2 9 5 9 5 0 8 4 1
 1 1 0 9 4 9 8 9 0 1 5 4 