# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent

# Best-MLP-DS1

#### Import data

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_1.csv", header=None)
dataset_val = pd.read_csv("dataset/val_1.csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_1.csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_1.csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1].values

#### Train Model

In [ ]:
param_grid = {
    'hidden_layer_sizes': [(30,50,), (10,10,10,)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['adam', 'sgd']
}
# Train model
cls = GridSearchCV(MLPClassifier(), param_grid)
cls.fit(X_train, Y_train)

#### VALIDATE - Predict using Validate set

In [ ]:
Y_val_pred = cls.predict(X_val)

#### VALIDATE - Output - Confusion matrix validate Set

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val, Y_val_pred)
cr = classification_report(Y_val, Y_val_pred)
print(Y_val_pred)
print(cm)
print(cr)

#### TEST - Predict using Test set

In [ ]:
Y_test_pred = cls.predict(X_test)

#### TEST - Output - Confusion matrix Test Set

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import csv

cm = confusion_matrix(Y_test, Y_test_pred)
cr = classification_report(Y_test, Y_test_pred)
print(cm)
print(cr)

#output result
pd.DataFrame(Y_test_pred).to_csv('output/Best-MLP-DS1.csv', header = None)
#append report
with open('output/Best-MLP-DS1.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr)


# Best-MLP-DS2

#### Import data

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_2.csv", header=None)
dataset_val = pd.read_csv("dataset/val_2.csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_2.csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_2.csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1].values

#### Train Model

In [2]:
param_grid = {
    'hidden_layer_sizes': [(30,50,), (10,10,10,)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['adam', 'sgd']
}
# Train model
cls2 = GridSearchCV(MLPClassifier(), param_grid)
cls2.fit(X_train, Y_train)

GridSearchCV(estimator=MLPClassifier(),
             param_grid={'activation': ['logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [(30, 50), (10, 10, 10)],
                         'solver': ['adam', 'sgd']})

#### VALIDATE - Predict using Validate set

In [3]:
Y_val_pred = cls2.predict(X_val)

#### VALIDATE - Output - Confusion matrix validate Set

In [4]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val, Y_val_pred)
cr = classification_report(Y_val, Y_val_pred)
print(Y_val_pred)
print(cm)
print(cr)

[9 7 1 ... 0 8 1]
[[150   0   0   0   8   0   0   0   5   2]
 [  3 363   0   2   2   1   1   1   2   0]
 [  1   1  34   0   0   1   0   0   7   1]
 [  1   4   0  36   2   2   0   0   0   0]
 [  6   1   1   1 116   4   0   0   4  17]
 [  1   4   0   2   1 149   1   0   1   6]
 [  0   3   0   0   0   0  41   0   0   1]
 [  1   0   0   1   0   3   0  40   0   0]
 [  4   7   4   0   2   2   2   0 126   3]
 [  2   3   2   0   8  11   2   0   5 342]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       165
           1       0.94      0.97      0.95       375
           2       0.83      0.76      0.79        45
           3       0.86      0.80      0.83        45
           4       0.83      0.77      0.80       150
           5       0.86      0.90      0.88       165
           6       0.87      0.91      0.89        45
           7       0.98      0.89      0.93        45
           8       0.84      0.84      0.84       150
          

#### TEST - Predict using Test set

In [6]:
Y_test_pred = cls2.predict(X_test)

#### TEST - Output - Confusion matrix Test Set

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import csv

cm = confusion_matrix(Y_test, Y_test_pred)
cr = classification_report(Y_test, Y_test_pred)
print(cm)
print(cr)

#output result
pd.DataFrame(Y_test_pred).to_csv('output/Best-MLP-DS2.csv', header = None)
#append report
with open('output/Best-MLP-DS2.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr)

[[ 50   1   0   2   0   1   0   0   0   1]
 [  1 120   0   1   0   1   0   0   2   0]
 [  0   0  10   0   0   1   0   0   4   0]
 [  1   0   0  13   0   1   0   0   0   0]
 [  4   1   0   0  37   2   0   0   2   4]
 [  0   0   0   0   1  50   0   0   0   4]
 [  1   2   1   0   0   0  10   0   1   0]
 [  0   0   0   0   0   0   0  15   0   0]
 [  0   1   0   0   0   0   0   0  48   1]
 [  2   0   2   0   6   5   0   0   3 107]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88        55
           1       0.96      0.96      0.96       125
           2       0.77      0.67      0.71        15
           3       0.81      0.87      0.84        15
           4       0.84      0.74      0.79        50
           5       0.82      0.91      0.86        55
           6       1.00      0.67      0.80        15
           7       1.00      1.00      1.00        15
           8       0.80      0.96      0.87        50
           9       0.91     