# Best-MLP
a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values:
* activation function: sigmoid, tanh, relu and identity 
* 2 network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10 
* solver: Adam and stochastic gradient descent

# Best-MLP-DS1

#### Import data

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_1.csv", header=None)
dataset_val = pd.read_csv("dataset/val_1.csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_1.csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_1.csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1].values

#### Train Model

In [2]:
param_grid = {
    'hidden_layer_sizes': [(30,50,), (10,10,10,)],
    'activation': ['logistic', 'tanh', 'relu', 'identity'],
    'solver': ['adam', 'sgd']
}
# Train model
cls = GridSearchCV(MLPClassifier(), param_grid)
cls.fit(X_train, Y_train)
cls = cls.best_estimator_
cls.fit(X_train, Y_train)

MLPClassifier(activation='identity', hidden_layer_sizes=(30, 50))

#### VALIDATE - Predict using Validate set

In [3]:
Y_val_pred = cls.predict(X_val)

#### VALIDATE - Output - Confusion matrix validate Set

In [4]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val, Y_val_pred)
cr = classification_report(Y_val, Y_val_pred)
print(Y_val_pred)
print(cm)
print(cr)

[ 1 17 12 12  1 16 17  9  3  0  3  4 21 24 25 10 18 15 11 15  5  8 19 13
 24 10 15 18 20  4 15 20 20  0 24 17 10 21  8 23  3 19 18 20 15  3 25 22
  8  2 10 21 12  7 16  9  2  6  3 14 11  6  3 13 23 14 17  9 22 11 10  8
  3  4  7 18  8  2 25 14 12  9  5 25  7 14  0 18 14 12 19 17 23  5 25 16
  2  0 13 25 20 11  0 13  7 15 10  9 13 13  5 18 11 14 22 21 10 17 18 17
  0 15 11 17 17 11 14  7 25 20 21 16 17  8 16 19 22 17 23 23  0  8 13  9
 14  6  6  1  3  6 22  1 12 15  5  9  4  8 20 22 13 25  0 12 23 16  4 12
 13 18 15 22  6 19 16 15 11 19 10  6  3  0  4  5 24 19 11 22 18  0  2 15
 21 15  9 21  2 10  4  1  8 24 15  0  7  5 18  2  2 13 15 21 10 16 11  6
  8  9 16 24  0 24  2 13 24  1 21 19 12 14  1 11 24 10 21 24  2  8  5]
[[ 9  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  6  0  0  0  1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   1  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  1  0  7  0  0  0 

#### TEST - Predict using Test set

In [6]:
Y_test_pred = cls.predict(X_test)

#### TEST - Output - Confusion matrix Test Set

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import csv

cm = confusion_matrix(Y_test, Y_test_pred)
cr = classification_report(Y_test, Y_test_pred)
print(cm)
print(cr)

#output result
pd.DataFrame(Y_test_pred).to_csv('output/Best-MLP-DS1.csv', header = None)
#append report
with open('output/Best-MLP-DS1.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr)


[[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

# Best-MLP-DS2

#### Import data

In [10]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#import data set according to selection
dataset_train = pd.read_csv("dataset/train_2.csv", header=None)
dataset_val = pd.read_csv("dataset/val_2.csv", header=None)
dataset_test = pd.read_csv("dataset/test_no_label_2.csv", header=None)
dataset_test_with_label = pd.read_csv("dataset/test_with_label_2.csv", header=None)

# X = data, Y = target
X_train = dataset_train.iloc[:, :-1].values
Y_train = dataset_train.iloc[:, -1].values
X_val = dataset_val.iloc[:, :-1].values
Y_val = dataset_val.iloc[:, -1].values
X_test = dataset_test.iloc[:, ].values
Y_test = dataset_test_with_label.iloc[:,-1].values

#### Train Model

In [11]:
param_grid = {
    'hidden_layer_sizes': [(30,50,), (10,10,10,)],
    'activation': ['logistic', 'tanh', 'relu', 'identity'],
    'solver': ['adam', 'sgd']
}
# Train model
cls2 = GridSearchCV(MLPClassifier(), param_grid)
cls2.fit(X_train, Y_train)
cls2 = cls2.best_estimator_
cls2.fit(X_train, Y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(30, 50), solver='sgd')

#### VALIDATE - Predict using Validate set

In [12]:
Y_val_pred = cls2.predict(X_val)

#### VALIDATE - Output - Confusion matrix validate Set

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val, Y_val_pred)
cr = classification_report(Y_val, Y_val_pred)
print(Y_val_pred)
print(cm)
print(cr)

[9 7 1 ... 8 0 1]
[[147   0   0   0   9   1   0   0   7   1]
 [  4 362   1   4   1   0   2   0   1   0]
 [  0   0  30   1   2   2   0   0   8   2]
 [  1   3   0  39   2   0   0   0   0   0]
 [  9   0   1   1 118   5   0   0   0  16]
 [  0   4   0   1   2 146   1   1   1   9]
 [  0   3   0   0   0   0  41   0   1   0]
 [  0   1   0   0   0   1   0  42   0   1]
 [  3   4   1   0   5   0   0   0 133   4]
 [  1   3   3   0   9   6   4   0   6 343]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       165
           1       0.95      0.97      0.96       375
           2       0.83      0.67      0.74        45
           3       0.85      0.87      0.86        45
           4       0.80      0.79      0.79       150
           5       0.91      0.88      0.90       165
           6       0.85      0.91      0.88        45
           7       0.98      0.93      0.95        45
           8       0.85      0.89      0.87       150
          

#### TEST - Predict using Test set

In [14]:
Y_test_pred = cls2.predict(X_test)

#### TEST - Output - Confusion matrix Test Set

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import csv

cm = confusion_matrix(Y_test, Y_test_pred)
cr = classification_report(Y_test, Y_test_pred)
print(cm)
print(cr)

#output result
pd.DataFrame(Y_test_pred).to_csv('output/Best-MLP-DS2.csv', header = None)
#append report
with open('output/Best-MLP-DS2.csv', 'a') as fd:
    fd.write('\n\nConfusion Matrix\n\n')
    fd.write(pd.DataFrame(cm).to_csv())
    fd.write('\n\n Classification Report\n\n')
    fd.write(cr)

[[ 52   0   1   1   0   1   0   0   0   0]
 [  1 121   0   1   0   0   0   0   2   0]
 [  0   0   8   0   1   0   0   0   4   2]
 [  0   0   0  15   0   0   0   0   0   0]
 [  4   1   0   1  36   2   0   0   2   4]
 [  0   0   0   0   1  51   0   0   0   3]
 [  2   2   1   0   0   0   9   0   1   0]
 [  0   0   0   0   0   0   0  15   0   0]
 [  0   1   0   0   0   0   0   0  47   2]
 [  1   0   1   0   8   5   1   0   4 105]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.90        55
           1       0.97      0.97      0.97       125
           2       0.73      0.53      0.62        15
           3       0.83      1.00      0.91        15
           4       0.78      0.72      0.75        50
           5       0.86      0.93      0.89        55
           6       0.90      0.60      0.72        15
           7       1.00      1.00      1.00        15
           8       0.78      0.94      0.85        50
           9       0.91     