# GNB-DS1

Gaussian Naive Bayes Classifier, with default parameter values

#### Import Libraries

In [41]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB

#### Import data

In [42]:
# Import dataset according to selection
dataset_train1 = pd.read_csv("dataset/train_1.csv", header=None)
dataset_val1 = pd.read_csv("dataset/val_1.csv",header=None)
dataset_test1 = pd.read_csv("dataset/test_no_label_1.csv",header=None)
dataset_test1_with_label = pd.read_csv("dataset/test_with_label_1.csv",header=None)

# X = data, Y = target 
X_train1 = dataset_train1.iloc[:, :-1].values
Y_train1 = dataset_train1.iloc[:, -1].values
X_val1 = dataset_val1.iloc[:, :-1].values
Y_val1 = dataset_val1.iloc[:, -1].values
X_test1 = dataset_test1.iloc[:, ].values
Y_test1 = dataset_test1_with_label.iloc[:,-1]

#### Train Model

In [44]:
classifier = GaussianNB()
classifier.fit(X_train1,Y_train1)

GaussianNB(priors=None, var_smoothing=1e-09)

#### VALIDATE - Predict using Validation Data

In [45]:
Y_val1_pred = classifier.predict(X_val1)

#### VALIDATE - Output - Confusion matrix validate Set

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# cm = confusion_matrix(Y_val1, Y_val1_pred)
# cr = classification_report(Y_val1, Y_val1_pred)
# print(Y_val1_pred)
# print(cm)
# print(cr)

#### TEST - Predict using Test set

In [37]:
Y_test1_pred = classifier.predict(X_test1)

#### Test - Output - Confusion matrix Test Set

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test1, Y_test1_pred)
cr = classification_report(Y_test1, Y_test1_pred)
print(cm)
print(cr)

# output result 
pd.DataFrame(Y_test1_pred).to_csv('output/GNB-DS1.csv', header = None)
# append report
with open('output/GNB-DS1.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

# GNB-DS2

#### Import Libraries

In [25]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB

#### Import Data

In [26]:
# Import dataset according to selection
dataset_train2 = pd.read_csv("dataset/train_2.csv", header=None)
dataset_val2 = pd.read_csv("dataset/val_2.csv",header=None)
dataset_test2 = pd.read_csv("dataset/test_no_label_2.csv",header=None)
dataset_test2_with_label = pd.read_csv("dataset/test_with_label_2.csv",header=None)

# X = data, Y = target 
X_train2 = dataset_train2.iloc[:, :-1].values
Y_train2 = dataset_train2.iloc[:, -1].values
X_val2 = dataset_val2.iloc[:, :-1].values
Y_val2 = dataset_val2.iloc[:, -1].values
X_test2 = dataset_test2.iloc[:, ].values
Y_test2 = dataset_test2_with_label.iloc[:,-1]

#### Train Model

In [27]:
classifier2 = GaussianNB()
classifier2.fit(X_train2,Y_train2)

GaussianNB(priors=None, var_smoothing=1e-09)

#### VALIDATE - Predict using Validation Data

In [33]:
Y_val2_pred = classifier2.predict(X_val2)

#### VALIDATE - Output - Confusion matrix validate Set

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_val2, Y_val2_pred)
cr = classification_report(Y_val2, Y_val2_pred)
print(Y_val2_pred)
print(cm)
print(cr)

[9 7 1 ... 1 4 1]
[[ 60  11   3  60  29   0   0   0   1   1]
 [ 14 341   2  14   1   2   0   1   0   0]
 [  6   0  29   0   0   1   4   0   2   3]
 [  1   3   1  40   0   0   0   0   0   0]
 [  5   1   6   7  68   4   8   0   1  50]
 [  5   0   4  11   6  91  14   0   2  32]
 [  0   1   0   0   0   0  42   0   1   1]
 [  1   3   0   1   0   0   0  39   0   1]
 [  6   6  65   2   0   1  16   1  48   5]
 [  6   2  10   2  11  19  63   0   1 261]]
              precision    recall  f1-score   support

           0       0.58      0.36      0.45       165
           1       0.93      0.91      0.92       375
           2       0.24      0.64      0.35        45
           3       0.29      0.89      0.44        45
           4       0.59      0.45      0.51       150
           5       0.77      0.55      0.64       165
           6       0.29      0.93      0.44        45
           7       0.95      0.87      0.91        45
           8       0.86      0.32      0.47       150
          

#### TEST - Predict using Test set

In [35]:
Y_test2_pred = classifier2.predict(X_test2)

#### Test - Output - Confusion matrix Test Set

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm2 = confusion_matrix(Y_test2, Y_test2_pred)
cr2 = classification_report(Y_test2, Y_test2_pred)
print(cm2)
print(cr2)

# output result 
pd.DataFrame(Y_test2_pred).to_csv('output/GNB-DS2.csv', header = None)
# append report
with open('output/GNB-DS2.csv','a') as f:
    f.write('\n\nConfusion Matrix\n\n')
    f.write(pd.DataFrame(cm2).to_csv())
    f.write('\n\n Classification Report\n\n')
    f.write(cr2)

[[ 26   4   1  14   8   1   0   0   1   0]
 [  6 111   1   6   0   1   0   0   0   0]
 [  0   0  12   0   1   0   0   0   1   1]
 [  1   0   0  14   0   0   0   0   0   0]
 [  2   0   1   6  20   2   4   0   0  15]
 [  0   0   1   1   1  34   8   0   0  10]
 [  3   1   0   0   0   0  11   0   0   0]
 [  0   1   0   0   0   0   0  14   0   0]
 [  1   2  26   0   0   0   5   0  15   1]
 [  4   1   1   0   4   7  17   0   0  91]]
              precision    recall  f1-score   support

           0       0.60      0.47      0.53        55
           1       0.93      0.89      0.91       125
           2       0.28      0.80      0.41        15
           3       0.34      0.93      0.50        15
           4       0.59      0.40      0.48        50
           5       0.76      0.62      0.68        55
           6       0.24      0.73      0.37        15
           7       1.00      0.93      0.97        15
           8       0.88      0.30      0.45        50
           9       0.77     